Android support
KrauseFx/fastlane-plugin-appicon pull request #9
Opened 2016-10-07 20:21 UTC by adrum

This is a pull request adding Android support for issue #7

2016-10-07 21:11 UTC, KrauseFx requested changes

2016-10-07 21:11 UTC, KrauseFx commented on README.md
> +    appicon_res_filename:'ic_launcher',
Trailing comma should be removed

2016-10-07 21:11 UTC, KrauseFx commented on README.md
> +    )
Please move this to the far left

2016-10-07 21:11 UTC, KrauseFx commented on fastlane/Fastfile
> +end
Missing new line at the end of the file

2016-10-07 21:11 UTC, KrauseFx commented on lib/fastlane/plugin/appicon/actions/appicon_action.rb
> +        [:ios, :mac, :macos, :caros, :android].include?(platform)
`:caros` cc @neonichu 😂

2016-10-07 21:12 UTC, KrauseFx commented
Hey @adrum, thanks for the PR. I added some comments to the documentation. Thinking about this, I'd prefer the Android part to be its own action within this plugin. To do that, duplicate the action in this directory (https://github.com/KrauseFx/fastlane-plugin-appicon/tree/master/lib/fastlane/plugin/appicon/actions) and name it `android_appicon`. This way we don't end up with so many possible parameters 👍

2016-10-08 23:57 UTC, adrum commented
Hey @KrauseFx, that's a great idea to separate android into its own action. I ended up only adding one parameter to the new android action when compared to the original action. I actually ran `rubocop -a` this time, too.

2016-10-09 20:28 UTC, KrauseFx approved these changes

2016-10-09 20:28 UTC, merged

2016-10-09 20:28 UTC, KrauseFx commented
Looks great, thanks 👍

2017-09-02 15:36 UTC, joshdholtz commented
@adrum Thanks for adding this to @KrauseFx's already awesome plugin ❤️